{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: percona-xtradb-cluster-operator
  labels:
    app: {{ template "pxc-operator.name" . }}
    chart: {{ template "pxc-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}
