## Default values for the image
replicaCount: 1

image:
  repository: percona/percona-server-mongodb-operator
  tag: 0.3.0
  pullPolicy: Always

## Install Default RBAC roles and bindings
rbac:
  create: true
  apiVersion: v1beta1

serviceAccount:
  psmdbOperatorServiceAccount:
    create: true
    name: default

deployments:
  psmdbOperator: true

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

## additional command arguments go here; will be translated to `--key=value` form
## e.g., analytics: true
commandArgs: {}

psmdbOperator:
  name: psmdb-operator

psmdbCluster:
  name: psmdb-cluster
  size: 3
