apiVersion: "pxc.percona.com/v1alpha1"
kind: "PerconaXtraDBCluster"
metadata:
  name: {{ .Values.pxcCluster.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "pxc-operator.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  finalizers:
    - delete-pxc-pods-in-order
spec:
  secretsName: my-cluster-secrets
  pxc:
    size: 3
    allowUnsafeConfigurations: false
    image: perconalab/pxc-openshift:0.2.0
    resources:
      requests:
        memory: 1G
        cpu: 600m
    podDisruptionBudget:
      maxUnavailable: 1
    volumeSpec:
      emptyDir: {}
  proxysql:
    enabled: false
    size: 1
    image: perconalab/proxysql-openshift:0.3.0
    resources:
      requests:
        memory: 1G
        cpu: 600m
    volumeSpec:
      emptyDir: {}
  pmm:
    enabled: false
    image: perconalab/pmm-client:1.17.0
    serverHost: monitoring-service
    serverUser: pmm
  backup:
    image: perconalab/backupjob-openshift:0.2.0
    storages:
      s3-us-west:
        type: s3
        s3:
          bucket: S3-BACKUP-BUCKET-NAME-HERE
          credentialsSecret: my-cluster-name-backup-s3
          region: us-west-2
      fs-pvc:
        type: filesystem
        volume:
          emptyDir: {}
    schedule:
      - name: "sat-night-backup"
        schedule: "0 0 * * 6"
        keep: 3
        storageName: s3-us-west
      - name: "daily-backup"
        schedule: "0 0 * * *"
        keep: 5
        storageName: fs-pvc

