{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pxc-operator.serviceAccountName" . }}
  labels:
    app: {{ template "pxc-operator.name" . }}
    chart: {{ template "pxc-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}
